services:
  backend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - "8000:8000" 
    volumes:
      - .:/app
      - /app/node_modules
    environment:
        NODE_ENV: development
        DATABASE_URL: mongodb://user:password@mongo:27017/myapp_dev?authSource=admin
    command: pnpm run dev
    depends_on:
      - database
  
  database:
    image: mongo:8.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password 
      MONGO_INITDB_DATABASE: myapp_dev
    volumes:
      - db_data:/data/db
    ports:
      - "27017:27017"

volumes:
  db_data
