services:
  backend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - "8000:8000" 
    volumes:
      - .:/app
      - /app/node_modules

    environment:
        NODE_ENV: developmentj

    command: pnpm run dev
  

  database:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:var/lib/postgres/data
    ports:
      - "5432:5432"

volumes:
  db_data
